### ISSUE TITLE
guide: multi-cmd example in a `dvc.yaml` sample

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2070]
> From https://github.com/iterative/dvc.org/pull/2062#pullrequestreview-559266804

A sample dvc.yaml file in https://dvc.org/doc/user-guide/project-structure/pipelines-files could have a multi-`cmd`

(OUTDATED) [The one in templating](https://dvc.org/doc/user-guide/project-structure/pipelines-files#templating) had this for some time but it was removed accidentally (it wasn't great anyway):

```yaml
    cmd:
      - pip install -r requirements.txt
      - python train.py --out ${model_file}
    deps:
      - requirements.txt
```

Ideas for a real-life example in https://github.com/iterative/dvc/issues/4373#issuecomment-751996212

Script to look for examples in GH: https://gist.github.com/skshetry/94d04f5b505d84ea614834617d647cde
