### ISSUE TITLE
ref: `exp run --set-param` with templating

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#2313]
It'd be great to have an example of experiments coupled with the parametrization (or at least a mention that it's possible?).

```yaml
# dvc.yaml
stages:
  build:
      cmd: python src/main.py ${test_size}
      deps:
        - src/main.py
      outs:
        - model.pickle
      metrics:
        - metrics.json:
            cache: false
```

```console
$ dvc exp run --set-param "test_size=0.5"
```
