### ISSUE TITLE
how-to: spot changes in the environment for pipelines

### ISSUE THREAD

**Issue by aguschin** [iterative/dvc.org#2502]
The results of `dvc repro` could be different if we update libraries in our environment, but still `dvc repro` won't spot that. It would be great to have some suggested solutions for this in the docs, for example, in "User Guide > How to". For typical python setup the workaround would to add stage with `pip freeze`, something like this:
```
stages:
  check-requirements:
    cmd: pip freeze > requirements.txt
    outs:
    - requirements.txt:
        cache: false
  first-stage-in-pipeline:
    deps:
    - requirements.txt
    ...
```

It there are other good solutions, would be great to add them too.
