### ISSUE TITLE
dvclive: update log_sklearn_plots

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4504]
### Report

`live.log_sklearn_plot` generates a `dvc.yaml` config with all the properties set like:

```yaml
plots:
- plots/sklearn/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
```

The docs need to be updated to show this. Right now, the docs suggest you need to manually add these properties.
