### ISSUE TITLE
lint: run prettier on all doc files

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#512]
See https://github.com/iterative/dvc.org/issues/512#issuecomment-518894225

---

~~A problem after implementing #372 seems to be that `pretty-quick` is that some lines inside md fenced code blocks, the ones starting with `-`, seem to be confused for bullets, and thus indented. E.g. everything starting at `path` would be indented in the sample below (from `static/docs/user-guide/external-dependencies.md`):~~

![image](https://user-images.githubusercontent.com/1477535/62179237-10d54280-b309-11e9-8c2d-cf52ddfa31c9.png)

~~The linter should simply ignore code blocks 🙂~~ OK'd by Ivan in https://github.com/iterative/dvc.org/issues/512#issuecomment-518878493

**Comment by jorgeorpinel** [comment]
Sorry to pick on you @algomaster99... But you may also be the best equipped person to give this one a first look. No worries either way but please lmk.

**Comment by algomaster99** [comment]
@jorgeorpinel I tried this but I couldn't reproduce the issue. I think `prettier` does ignore the indentation inside the code block.
![bug](https://user-images.githubusercontent.com/35191225/62180765-c8507000-b36e-11e9-83c2-48bfdef1812a.gif)

**Comment by jorgeorpinel** [comment]
Not sure it's `prettier` or what. It happens when I try to `git commit` the file with any other change in it.

**Comment by algomaster99** [comment]
@jorgeorpinel I can still not reproduce this. But if it does, please send a screenshot again of the latest code (the above image seems outdated).
To my knowledge, prettier doesn't interfere with the indentation since that will throw errors. Check [this](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKADLBPAhgWwBt0ATOABwGcl0BaAAjhlwHMl6ByVEAMwBYAzACY4QgOwAGMCQBsAvmACsARiEBOGXGlCARmCE9FcMYqG1F3LlHr1yuGAAt2DmDCpIA9B5IA3MADoIACcWD0oBDxYmWkpmIPgSb3tcfwAPInQIAFcYajp6fBJFdlwBCT5cHh0NCRkJXFwSNQllMRkhGQAOeSNlCQFFC2tbeyd6EmS0jOGwXDAHOHYYIKy4dBt8JiCASzB2HlxCSjXh8jggym3Y-cPj9CwMEAAaEAhyGG3oSmRQXCCgiAAdwACn8EN8ULgfBBtiRniAdEE5gBrJgAZTsYG2UBYyGWqxeLiIAHUHNt4JRMXA0eDydsfOTsMhwJRvi9scd4sCkSx8LhkAcjnAXgArSipABCSLAqJgaIIcAAMti4ALbsKQGLUmjsSxCHAAIpZCDwNVCl52C7nZl8oLIkhAqDw8g7WDE2GOZCdCQWgHHYlI8jMl1wTk+VUvACOxvg3LeEJAuEotCgcDgZDhLyCcGj22z3NYfLNxxex3w2zxKw1lxx+qNJtVSEFJZAzB07pInqQQhey1w20IuoAwhB8EWUFBoBGQFljgAVXA6CHNuAAX1XQA) playground out.

If the error still persists, we can resort to this method (which I don't prefer to be honest :sweat_smile: ):
```
<!-- prettier-ignore -->
```js
ugly   ( code ) ;
```

**Comment by jorgeorpinel** [comment]
Just **change anything** in `static/docs/commands-reference/import-url.md` (**outside of YAML code blocks**) and try to `git commit` your change. It will indent parts of the YAML code block contents:

![Screen Recording 2019-08-04 at 01 59 50 2019-08-04 02_08_11](https://user-images.githubusercontent.com/1477535/62421309-c4696a00-b65c-11e9-9efa-ace7f3ae06f4.gif)

> p.s. creating this gif took a long time. What did you make them with again? Thanks

**Comment by algomaster99** [comment]
@jorgeorpinel 
This is really strange :open_mouth: 
![weird](https://user-images.githubusercontent.com/35191225/62422000-df71c380-b6c8-11e9-94aa-e2d2b02c7b05.gif)
Can you check your `prettier` version in `package-lock.json`? Mine is `1.17.0`.

#### Creating screencasts
1. Download this software: https://www.maartenbaert.be/simplescreenrecorder/
2. Use [this link](https://ezgif.com/video-to-gif) to convert the `.mp4` video - created from the above software to a `.gif`.

**Comment by jorgeorpinel** [comment]
It's the same version. In your screenshots the lines in question are already indented as that's the master branch. But the actual DVC-files don't have that indentation so I've [un-indented them](https://github.com/iterative/dvc.org/pull/509/files#diff-0a462fb4a411db0aa4af5e0a1036b7f0L202-R187) in my fork. Please un-indent them (or use my fork) to reproduce the issue.

**Comment by algomaster99** [comment]
@jorgeorpinel I think both are valid syntaxes. Refer to [this link](https://yamlchecker.com/).
### Current
```
md5: 7de90e7de7b432ad972095bc1f2ec0f8
wdir: .
deps:
- path: data/data.xml
  repo:
    url: git@github.com:iterative/example-get-started
    rev_lock: 6c73875a5f5b522f90b5afa9ab12585f64327ca7
outs:
- md5: a304afb96060aad90176268345e10355
  path: data.xml
  cache: true
  metric: false
  persist: false
```
### Prettier formatting
```
md5: 7de90e7de7b432ad972095bc1f2ec0f8
wdir: .
deps:
  - path: data/data.xml
    repo:
      url: git@github.com:iterative/example-get-started
      rev_lock: 6c73875a5f5b522f90b5afa9ab12585f64327ca7
outs:
  - md5: a304afb96060aad90176268345e10355
    path: data.xml
    cache: true
    metric: false
    persist: false
```

Please refer to this [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbAJgViQAgOzpwCcADHAeQEYAsAzAEwCG6Re9JRmlYAjAGb04YEnwAcAHSgB3dAEsATrgB0kwgAcAzkkkBaHGsYwAFrnSHGAejMxGSgB6oANpJw55cNRG1RXrgK7yjrgA5rIwAAKhxn6USpCoSGFw8oayAG5wFnB2jKhqjnA6wXAwOho28vDoLr7uaQD6jhBgANa4AGxgeLSieJiMmHxcmPT0fKSU-XyMRIyUPPSYooPtdPR4YIx4khB+MFq6OBjYOIy0JNSMfJRE7SR3jMykPHjt9O2itNSYcDwktJhMDUDMZTOZ7E4apswEY4LgYPI-HAaqgSvJZGBcNNHBpkT59MkNLJyljGDi4CAADQgCBqGCyaAaZCgRjyeQQKQABVZCCZKEYaQgsnQVJAlBSrRKAGUDGBZFBgsgEUjqUYYE4AOpGJIaWVwKW8sLpMIAT2Q4A0TOp8txlU5KWCqEYyGxuOpACsNHYAEISlrS3JwAAy8opSFdcA9Xql8uCBQAin4IPAXWS3SADPJbeaTblHKK1OjYBrhcZkKISNTCxBcRqUmpzYW4LaMqKAI5J+D22l8kCMDQ6KBwOCEEXU9wdhRwe2MR3O8NpyMgXGoWRKxFLokKhOdsMR6k2Sgl9BlpD0A8pWSOWMAYQgqCd5qg0Ap1L8uIAKnM+RGAL6-oA) too. Prettier just format it the way it is configured. I couldn't find any option to toggle it.
